export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAIL = 'GET_ARTICLE_LIST_FAIL';

export const GET_AUTHOR_ARTICLE_LIST_SUCCESS = 'GET_AUTHOR_ARTICLE_LIST_SUCCESS';
export const GET_AUTHOR_ARTICLE_LIST_FAIL = 'GET_AUTHOR_ARTICLE_LIST_FAIL';

export const GET_ARTICLE_LIST_CATEGORIES_SUCCESS = 'GET_ARTICLE_LIST_CATEGORIES_SUCCESS';
export const GET_ARTICLE_LIST_CATEGORIES_FAIL = 'GET_ARTICLE_LIST_CATEGORIES_FAIL';

export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAIL = 'GET_ARTICLE_FAIL';

export const GET_SEARCH_ARTICLE_SUCCESS = 'GET_SEARCH_ARTICLE_SUCCESS';
export const GET_SEARCH_ARTICLE_FAIL = 'GET_SEARCH_ARTICLE_FAIL';